// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

namespace CommandLineGenerator.Emitters;

/// <summary>
/// Emits the generated attribute classes used to decorate user code.
/// </summary>
internal static class AttributesEmitter
{
    /// <summary>
    /// Generates the source code for all marker attributes.
    /// </summary>
    public static string Emit()
    {
        return """
            // <auto-generated/>
            #nullable enable

            namespace CommandLineGenerator;

            /// <summary>
            /// Marks a method as a CLI command. The method parameters should be options types
            /// decorated with <see cref="MapCommandLineOptionsAttribute"/>.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
            internal sealed class CommandAttribute : global::System.Attribute
            {
                public CommandAttribute(string name) => Name = name;
                public CommandAttribute() => Name = "";

                /// <summary>The command name. Empty string for root command.</summary>
                public string Name { get; }

                /// <summary>Description shown in help text.</summary>
                public string? Description { get; set; }
            }

            /// <summary>
            /// Marks a record or class as a container for command-line options and arguments.
            /// Properties without attributes become options; use <see cref="ArgumentAttribute"/> for arguments.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
            internal sealed class MapCommandLineOptionsAttribute : global::System.Attribute
            {
                /// <summary>
                /// When true (default), property names are converted to kebab-case for option names.
                /// </summary>
                public bool UseKebabCase { get; set; } = true;
            }

            /// <summary>
            /// Marks a parameter or property as a CLI option with explicit configuration.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
            internal sealed class OptionAttribute : global::System.Attribute
            {
                /// <summary>The primary option name (e.g., "--verbose"). If null, derived from property name.</summary>
                public string? Name { get; set; }

                /// <summary>Short alias (e.g., "-v").</summary>
                public string? Alias { get; set; }

                /// <summary>Description shown in help text.</summary>
                public string? Description { get; set; }
            }

            /// <summary>
            /// Marks a parameter or property as a positional CLI argument.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Parameter | global::System.AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
            internal sealed class ArgumentAttribute : global::System.Attribute
            {
                /// <summary>The argument name shown in help text.</summary>
                public string? Name { get; set; }

                /// <summary>Description shown in help text.</summary>
                public string? Description { get; set; }
            }
            """;
    }
}
