// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

using System.Collections.Immutable;
using StaticCs;

namespace CommandLineGenerator.Emitters;

/// <summary>
/// Emits the CommandExtensions class with the AddOptions&lt;T&gt; extension method.
/// </summary>
internal static class CommandExtensionsEmitter
{
    /// <summary>
    /// Generates the source code for the CommandExtensions class.
    /// Returns null if there are no options types.
    /// </summary>
    public static string? Emit(ImmutableArray<OptionsTypeInfo?> optionsTypes)
    {
        var validTypes = optionsTypes.OfType<OptionsTypeInfo>().ToList();
        if (validTypes.Count == 0)
            return null;

        var builder = new IndentingBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.CommandLine;");
        builder.AppendLine("");
        builder.AppendLine("namespace CommandLineGenerator;");
        builder.AppendLine("");
        builder.AppendLine("internal static class CommandExtensions");
        builder.AppendLine("{");
        builder.Indent();

        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Adds all arguments and options from the specified options type to the command.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("public static void AddOptions<T>(this Command command)");
        builder.AppendLine("{");
        builder.Indent();

        for (int i = 0; i < validTypes.Count; i++)
        {
            var opt = validTypes[i];
            var prefix = i == 0 ? "if" : "else if";
            var mapperName = Utilities.GetMapperName(opt);

            builder.AppendLine($"{prefix} (typeof(T) == typeof({opt.FullTypeName}))");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine($"{mapperName}.AddTo(command);");
            builder.Dedent();
            builder.AppendLine("}");
        }

        builder.AppendLine("else");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine(
            "throw new InvalidOperationException($\"Type '{typeof(T).FullName}' is not a mapped options type.\");"
        );
        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");

        return builder.ToString();
    }
}
