// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

using System.Collections.Immutable;
using StaticCs;

namespace CommandLineGenerator.Emitters;

/// <summary>
/// Emits the ConsoleApp and ConsoleAppBuilder classes for hosting-based CLI applications.
/// </summary>
internal static class ConsoleAppEmitter
{
    /// <summary>
    /// Generates the source code for ConsoleApp and ConsoleAppBuilder.
    /// Returns null if there are no commands.
    /// </summary>
    public static string? Emit(
        ImmutableArray<CommandMethodInfo?> commands,
        Dictionary<string, OptionsTypeInfo> optionsTypes
    )
    {
        var validCommands = commands.OfType<CommandMethodInfo>().ToList();
        if (validCommands.Count == 0)
            return null;

        var builder = new IndentingBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.CommandLine;");
        builder.AppendLine("using System.Diagnostics.CodeAnalysis;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("using Microsoft.Extensions.Hosting;");
        builder.AppendLine("");
        builder.AppendLine("namespace CommandLineGenerator;");
        builder.AppendLine("");

        // Generate ConsoleApp static class
        EmitConsoleAppClass(builder);

        builder.AppendLine("");

        // Generate ConsoleAppBuilder
        EmitConsoleAppBuilderClass(builder, validCommands, commands, optionsTypes);

        return builder.ToString();
    }

    private static void EmitConsoleAppClass(IndentingBuilder builder)
    {
        builder.AppendLine("internal static class ConsoleApp");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("public static ConsoleAppBuilder CreateBuilder(string[] args) => new(args);");
        builder.Dedent();
        builder.AppendLine("}");
    }

    private static void EmitConsoleAppBuilderClass(
        IndentingBuilder builder,
        List<CommandMethodInfo> validCommands,
        ImmutableArray<CommandMethodInfo?> commands,
        Dictionary<string, OptionsTypeInfo> optionsTypes
    )
    {
        builder.AppendLine("internal sealed class ConsoleAppBuilder");
        builder.AppendLine("{");
        builder.Indent();

        // Fields
        builder.AppendLine("private readonly string[] _args;");
        builder.AppendLine("private readonly List<Func<IServiceProvider, Command>> _commandFactories = [];");
        builder.AppendLine("private Func<IServiceProvider, RootCommand>? _rootCommandFactory;");
        builder.AppendLine("");

        // Constructor
        EmitConstructor(builder);

        builder.AppendLine("");
        builder.AppendLine("public HostApplicationBuilder Host { get; }");
        builder.AppendLine("");

        // AddCommand<T>
        EmitAddCommandMethod(builder, validCommands);

        builder.AppendLine("");

        // Generate private factory methods for each command method
        foreach (var cmd in commands)
        {
            if (cmd is null)
                continue;

            EmitCommandFactory(builder, cmd, optionsTypes);
            builder.AppendLine("");
        }

        // RunAsync
        EmitRunAsyncMethod(builder);

        builder.Dedent();
        builder.AppendLine("}");
    }

    private static void EmitConstructor(IndentingBuilder builder)
    {
        builder.AppendLine("internal ConsoleAppBuilder(string[] args)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("_args = args;");
        builder.AppendLine("var settings = new HostApplicationBuilderSettings { Args = args };");
        builder.AppendLine("Host = Microsoft.Extensions.Hosting.Host.CreateEmptyApplicationBuilder(settings);");
        builder.Dedent();
        builder.AppendLine("}");
    }

    private static void EmitAddCommandMethod(IndentingBuilder builder, List<CommandMethodInfo> validCommands)
    {
        builder.AppendLine(
            "public ConsoleAppBuilder AddCommand<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] T>() where T : class"
        );
        builder.AppendLine("{");
        builder.Indent();

        var containingClasses = validCommands.GroupBy(c => c.ContainingClassFullName).ToList();

        if (containingClasses.Count > 0)
        {
            for (int i = 0; i < containingClasses.Count; i++)
            {
                var group = containingClasses[i];
                var prefix = i == 0 ? "if" : "else if";
                var firstCmd = group.First();

                builder.AppendLine($"{prefix} (typeof(T) == typeof({firstCmd.ContainingClassFullName}))");
                builder.AppendLine("{");
                builder.Indent();
                builder.AppendLine($"Host.Services.AddTransient<{firstCmd.ContainingClassFullName}>();");

                foreach (var cmd in group)
                {
                    var factoryName = $"Create{firstCmd.ContainingClassName}_{cmd.MethodName}";
                    if (cmd.IsRoot)
                    {
                        builder.AppendLine($"_rootCommandFactory = sp => {factoryName}(sp);");
                    }
                    else
                    {
                        builder.AppendLine($"_commandFactories.Add(sp => {factoryName}(sp));");
                    }
                }

                builder.Dedent();
                builder.AppendLine("}");
            }

            builder.AppendLine("else");
            builder.AppendLine("{");
            builder.Indent();
            builder.AppendLine(
                "throw new InvalidOperationException($\"Type '{typeof(T).FullName}' is not a registered command class.\");"
            );
            builder.Dedent();
            builder.AppendLine("}");
        }
        else
        {
            builder.AppendLine(
                "throw new InvalidOperationException($\"Type '{typeof(T).FullName}' is not a registered command class.\");"
            );
        }

        builder.AppendLine("");
        builder.AppendLine("return this;");
        builder.Dedent();
        builder.AppendLine("}");
    }

    private static void EmitCommandFactory(
        IndentingBuilder builder,
        CommandMethodInfo cmd,
        Dictionary<string, OptionsTypeInfo> optionsTypes
    )
    {
        var returnType = cmd.IsRoot ? "RootCommand" : "Command";
        var factoryName = $"Create{cmd.ContainingClassName}_{cmd.MethodName}";

        builder.AppendLine($"private static {returnType} {factoryName}(IServiceProvider sp)");
        builder.AppendLine("{");
        builder.Indent();

        builder.AppendLine($"var instance = sp.GetRequiredService<{cmd.ContainingClassFullName}>();");
        builder.AppendLine("");

        // Create the command
        if (cmd.IsRoot)
        {
            builder.AppendLine("var command = new RootCommand();");
        }
        else
        {
            builder.AppendLine($"var command = new Command(\"{cmd.CommandName}\");");
        }

        if (cmd.Description is not null)
        {
            builder.AppendLine($"command.Description = \"{Utilities.EscapeString(cmd.Description)}\";");
        }

        builder.AppendLine("");

        // Add arguments and options from each mapper
        foreach (var optTypeName in cmd.OptionsTypeNames)
        {
            if (optionsTypes.TryGetValue(optTypeName, out var optType))
            {
                var mapperName = Utilities.GetMapperName(optType);
                builder.AppendLine($"{mapperName}.AddTo(command);");
            }
        }

        builder.AppendLine("");
        builder.AppendLine("command.SetAction(async (parseResult, ct) =>");
        builder.AppendLine("{");
        builder.Indent();

        // Parse options using mappers
        var optionVarNames = new List<string>();
        int optIdx = 0;
        foreach (var optTypeName in cmd.OptionsTypeNames)
        {
            if (optionsTypes.TryGetValue(optTypeName, out var optType))
            {
                var mapperName = Utilities.GetMapperName(optType);
                var optVarName = $"options{optIdx}";
                optionVarNames.Add(optVarName);

                builder.AppendLine($"var {optVarName} = {mapperName}.Parse(parseResult);");
                optIdx++;
            }
        }

        // Call the method
        var methodArgs = string.Join(", ", optionVarNames);
        if (cmd.IsAsync)
        {
            builder.AppendLine($"await instance.{cmd.MethodName}({methodArgs});");
        }
        else
        {
            builder.AppendLine($"instance.{cmd.MethodName}({methodArgs});");
        }

        builder.Dedent();
        builder.AppendLine("});");
        builder.AppendLine("");
        builder.AppendLine("return command;");

        builder.Dedent();
        builder.AppendLine("}");
    }

    private static void EmitRunAsyncMethod(IndentingBuilder builder)
    {
        builder.AppendLine("public async Task<int> RunAsync()");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("Host.Services.AddSingleton<RootCommand>(sp =>");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("RootCommand root = _rootCommandFactory is not null");
        builder.AppendLine("    ? _rootCommandFactory(sp)");
        builder.AppendLine("    : new RootCommand();");
        builder.AppendLine("");
        builder.AppendLine("foreach (var factory in _commandFactories)");
        builder.AppendLine("{");
        builder.Indent();
        builder.AppendLine("root.Subcommands.Add(factory(sp));");
        builder.Dedent();
        builder.AppendLine("}");
        builder.AppendLine("");
        builder.AppendLine("return root;");
        builder.Dedent();
        builder.AppendLine("});");
        builder.AppendLine("");
        builder.AppendLine("var host = Host.Build();");
        builder.AppendLine("var rootCommand = host.Services.GetRequiredService<RootCommand>();");
        builder.AppendLine("return await rootCommand.Parse(_args).InvokeAsync();");
        builder.Dedent();
        builder.AppendLine("}");
    }
}
