// SPDX-FileCopyrightText: Copyright (c) 2026 Logan Bussell
// SPDX-License-Identifier: MIT

#nullable enable

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using StaticCs;

namespace SystemCommandLineGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class CommandLineGenerator : IIncrementalGenerator
{
    private const string CommandAttributeName = "SystemCommandLineGenerator.CommandAttribute";
    private const string ArgumentAttributeName = "SystemCommandLineGenerator.ArgumentAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandClasses = context
            .SyntaxProvider.ForAttributeWithMetadataName(
                CommandAttributeName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetCommandInfo(ctx, ct)
            )
            .Where(static c => c is not null)!;

        // Collect all commands and generate a single registry file
        var allCommands = commandClasses.Collect();

        context.RegisterSourceOutput(
            allCommands,
            static (spc, commands) =>
            {
                if (commands.Length == 0)
                    return;

                GenerateCommandRegistry(spc, commands!);
            }
        );
    }

    private static CommandInfo? GetCommandInfo(
        GeneratorAttributeSyntaxContext ctx,
        CancellationToken ct
    )
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;

        var commandAttr = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == CommandAttributeName
        );

        if (commandAttr is null)
            return null;

        var commandName =
            commandAttr.ConstructorArguments.Length > 0
                ? commandAttr.ConstructorArguments[0].Value as string ?? classSymbol.Name
                : classSymbol.Name;

        var executeMethod = classSymbol
            .GetMembers()
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m => m.Name == "ExecuteAsync");

        if (executeMethod is null)
            return null;

        var arguments = executeMethod
            .Parameters.Where(p =>
                p.GetAttributes()
                    .Any(a => a.AttributeClass?.ToDisplayString() == ArgumentAttributeName)
            )
            .Select(p => new ArgumentInfo(
                p.Name,
                p.Type.ToDisplayString(),
                p.HasExplicitDefaultValue,
                p.HasExplicitDefaultValue
                    ? FormatDefaultValue(p.ExplicitDefaultValue, p.Type)
                    : null
            ))
            .ToImmutableArray();

        return new CommandInfo(
            classSymbol.ContainingNamespace.ToDisplayString(),
            classSymbol.Name,
            commandName,
            arguments
        );
    }

    private static string FormatDefaultValue(object? value, ITypeSymbol type)
    {
        if (value is null)
            return "null";

        if (type.SpecialType == SpecialType.System_String)
            return $"\"{value}\"";

        if (type.SpecialType == SpecialType.System_Boolean)
            return value.ToString()!.ToLowerInvariant();

        return value.ToString()!;
    }

    private static void GenerateCommandRegistry(
        SourceProductionContext ctx,
        ImmutableArray<CommandInfo?> commands
    )
    {
        var builder = new IndentingBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.CommandLine;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("");
        builder.AppendLine("namespace SystemCommandLineGenerator;");
        builder.AppendLine("");

        builder.AppendLine("internal static class GeneratedCommands");
        builder.AppendLine("{");
        builder.Indent();

        // Generate a factory method for each command
        foreach (var cmd in commands)
        {
            if (cmd is null)
                continue;

            GenerateCommandFactory(builder, cmd);
            builder.AppendLine("");
        }

        // Generate a module initializer to register all commands
        builder.AppendLine("[System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("internal static void RegisterCommands()");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var cmd in commands)
        {
            if (cmd is null)
                continue;

            var fullTypeName = $"typeof(global::{cmd.Namespace}.{cmd.ClassName})";
            builder.AppendLine(
                $"GeneratedCommandRegistry.Register({fullTypeName}, \"{cmd.CommandName}\", {cmd.IsRoot.ToString().ToLowerInvariant()}, Create{cmd.ClassName});"
            );
        }

        builder.Dedent();
        builder.AppendLine("}");

        builder.Dedent();
        builder.AppendLine("}");

        ctx.AddSource("GeneratedCommands.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void GenerateCommandFactory(IndentingBuilder builder, CommandInfo info)
    {
        var fullTypeName = $"global::{info.Namespace}.{info.ClassName}";

        builder.AppendLine(
            $"public static Command Create{info.ClassName}(IServiceProvider serviceProvider)"
        );
        builder.AppendLine("{");
        builder.Indent();

        builder.AppendLine($"var instance = serviceProvider.GetRequiredService<{fullTypeName}>();");
        builder.AppendLine("");

        // Create arguments
        foreach (var arg in info.Arguments)
        {
            if (arg.HasDefaultValue)
            {
                builder.AppendLine(
                    $"var {arg.Name}Argument = new Argument<{arg.TypeName}>(\"{arg.Name}\") {{ DefaultValueFactory = _ => {arg.DefaultValue} }};"
                );
            }
            else
            {
                builder.AppendLine(
                    $"var {arg.Name}Argument = new Argument<{arg.TypeName}>(\"{arg.Name}\");"
                );
            }
        }

        if (info.Arguments.Length > 0)
            builder.AppendLine("");

        // Create the command
        if (info.IsRoot)
        {
            builder.AppendLine("var command = new RootCommand();");
        }
        else
        {
            builder.AppendLine($"var command = new Command(\"{info.CommandName}\");");
        }

        foreach (var arg in info.Arguments)
        {
            builder.AppendLine($"command.Arguments.Add({arg.Name}Argument);");
        }

        builder.AppendLine("");
        builder.AppendLine("command.SetAction(async (parseResult, ct) =>");
        builder.AppendLine("{");
        builder.Indent();

        foreach (var arg in info.Arguments)
        {
            builder.AppendLine($"var {arg.Name}Value = parseResult.GetValue({arg.Name}Argument)!;");
        }

        var argValues = string.Join(", ", info.Arguments.Select(a => $"{a.Name}Value"));
        builder.AppendLine($"await instance.ExecuteAsync({argValues});");

        builder.Dedent();
        builder.AppendLine("});");
        builder.AppendLine("");
        builder.AppendLine("return command;");

        builder.Dedent();
        builder.AppendLine("}");
    }

    private sealed record CommandInfo(
        string Namespace,
        string ClassName,
        string CommandName,
        ImmutableArray<ArgumentInfo> Arguments
    )
    {
        public bool IsRoot => string.IsNullOrEmpty(CommandName);
    }

    private sealed record ArgumentInfo(
        string Name,
        string TypeName,
        bool HasDefaultValue,
        string? DefaultValue
    );
}
